export const projects = [
    {
        id: 1,
        link: '/routes/projects/RHR',
        image: '/projects/images/desktop/1.webp',
        imageMobile: '/projects/images/mobile/1.webp',
        videoSrc: '/projects/videos/1.mp4',
        videoType: 'video/mp4; codecs=hvc1',
        videoSrc2: '/projects/videos/1.webm',
        videoType2: 'video/webm; codecs=vp9',
        title: 'Running Heroes Russia (RHR)',
        description: 'White Bride Ultra Gelendzhik',
        smallDescription: 'Событие, логодизайн, фирменный стиль, брендинг',
    },
    {
        id: 2,
        link: '/routes/projects/FHR',
        image: '/projects/images/desktop/2.webp',
        imageMobile: '/projects/images/mobile/2.webp',
        title: 'Федерация Хоккея России (FHR)',
        description: '75 лет великой истории СССР – Канада',
        smallDescription: 'Лендинг',
    },
    {
        id: 3,
        link: '/routes/projects/SBC',
        image: '/projects/images/desktop/3.webp',
        imageMobile: '/projects/images/mobile/3.webp',
        title: 'Спорт Бизнес Консалтинг (SBC)',
        description: 'Редизайн сайта «СБК»',
        smallDescription: 'UX/UI дизайн',
    },
    {
        id: 4,
        link: '/routes/projects/NHLiga-Festival',
        image: '/projects/images/desktop/4.webp',
        imageMobile: '/projects/images/mobile/4.webp',
        videoSrc: '/projects/videos/4.mp4',
        videoType: 'video/mp4; codecs=hvc1',
        videoSrc2: '/projects/videos/4.webm',
        videoType2: 'video/webm; codecs=vp9',
        title: 'Ночная Лига (NHLiga)',
        description: '«Фестиваль хоккея 2021», Сочи, 3-16 мая',
        smallDescription: 'Ключевой образ, событие, брендирование',
    },
    {
        id: 5,
        link: '/routes/projects/NewishSport',
        image: '/projects/images/desktop/5.webp',
        imageMobile: '/projects/images/mobile/5.webp',
        title: 'СNewish Sport',
        description: 'Newish Sport',
        smallDescription: 'Бренд, логотип, стиль',
    },
    {
        id: 6,
        link: '/routes/projects/SamboCup',
        image: '/projects/images/desktop/6.webp',
        imageMobile: '/projects/images/mobile/6.webp',
        title: 'Международная Федерация Самбо (FIAS)',
        description:
            'Continental championship «Open European SAMBO cup. Romania», 2021 ',
        smallDescription: 'Логотип, стиль',
    },
    {
        id: 7,
        link: '/routes/projects/NHLiga',
        image: '/projects/images/desktop/7.webp',
        imageMobile: '/projects/images/mobile/7.webp',
        title: 'Ночная Лига (NHLiga)',
        description: 'Редизайн сайта Ночной Хоккейной Лиги',
        smallDescription: 'UX/UI-дизайн, лендинг',
    },
    {
        id: 8,
        link: '/routes/projects/LoxinoIslanders',
        image: '/projects/images/desktop/8.webp',
        imageMobile: '/projects/images/mobile/8.webp',
        title: 'Loxino Islanders',
        description: 'Логотип клуба Loxino Islanders',
        smallDescription: 'Логодизайн',
    },
    {
        id: 9,
        link: '/routes/projects/SportExpress',
        image: '/projects/images/desktop/9.webp',
        imageMobile: '/projects/images/mobile/9.webp',
        title: 'Спорт-Экспресс',
        description: 'Юбилейный мерч к 30-летию «Спорт-Экспресс»',
        smallDescription: 'Атрибутика',
    },
];

export const moreprojects = [
    {
        id: 1,
        link: '/routes/projects-more/FHR',
        title: 'Национальная программа подготовки хоккеистов, 2017',
        imageSrc: '/projects/more-projects/1.webp',
    },
    {
        id: 2,
        link: '/routes/projects-more/VHL',
        title: 'Русская классика ВХЛ, Москва, 2017г',
        imageSrc: '/projects/more-projects/2.webp',
    },
    {
        id: 3,
        link: '/routes/projects-more/IIHF',
        title: 'Кубок мира среди молодёжных клубных команд, Татарстан, 2016 ',
        imageSrc: '/projects/more-projects/3.webp',
    },
    {
        id: 4,
        link: '/routes/projects-more/NHLiga',
        title: 'Кубок Чемпионов» — серия логотипов',
        imageSrc: '/projects/more-projects/4.webp',
    },
    {
        id: 5,
        link: '/routes/projects-more/CrazyOwl',
        title: 'Ультрамарафон Crazy Owl 50',
        imageSrc: '/projects/more-projects/5.webp',
    },
]

export const services = [
    {
        id: 1,
        title: 'Дизайн',
        subtitles: ['Логодизайн', 'Редизайн бренда', 'Кастомная разработка'],
        color: 'blue',
    },
    {
        id: 2,
        title: 'Брендинг',
        subtitles: [
            'Дизайн-системы',
            'Событийний брендинг',
            'Клубная айдентика',
        ],
        color: 'blue',
    },
    {
        id: 3,
        title: 'UX/UI',
        subtitles: ['Дизайн интерфейса', 'Мобильные решения', 'Спецпроекты'],
        color: 'blue',
    },
    {
        id: 4,
        title: 'Опции',
        subtitles: ['Платформа бренда', 'Дизайн-аудит', 'Медиакит, ивентбук'],
        color: 'red',
    },
    {
        id: 5,
        title: 'Сервис',
        subtitles: [
            'Сопровождеие бренда',
            'Техническое партнёрство',
            'Производственные услуги',
        ],
        color: 'red',
    },
];
